### ISSUE TITLE
Add support of `yamllint` in CI

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE-QA/x2t-testing#463]
Like here:
https://github.com/ONLYOFFICE/ooxml_parser/blob/master/.github/workflows/linting.yml#L6

**Comment by ShockwaveNN** [comment]
Default config is:
https://github.com/ONLYOFFICE/ooxml_parser/blob/master/.yamllint.yml

**Comment by l8556** [comment]
https://github.com/ONLYOFFICE-QA/x2t-testing/pull/466
